spring:
  application:
    name: api-gateway-service

server:
  port: 8765

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

cloud:
  gateway:
    routes:
      - id: IDENTITY-SERVICE
        uri: lb://IDENTITY-SERVICE
        predicates:
          - Path=/identity/**
        filters:
          - StripPrefix=1
      - id: USER-SERVICE
        uri: lb://USER-SERVICE
        predicates:
          - Path=/management/**
        filters:
          - StripPrefix=1
